[2024-11-05T10:23:29.155-0800] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-05T10:23:29.172-0800] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: aasnowflake_test_dag.run_query manual__2024-11-05T18:23:26.152290+00:00 [queued]>
[2024-11-05T10:23:29.176-0800] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: aasnowflake_test_dag.run_query manual__2024-11-05T18:23:26.152290+00:00 [queued]>
[2024-11-05T10:23:29.177-0800] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2024-11-05T10:23:29.183-0800] {taskinstance.py:2889} INFO - Executing <Task(SnowflakeOperator): run_query> on 2024-11-05 18:23:26.152290+00:00
[2024-11-05T10:23:29.186-0800] {standard_task_runner.py:72} INFO - Started process 87426 to run task
[2024-11-05T10:23:29.190-0800] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'aasnowflake_test_dag', 'run_query', 'manual__2024-11-05T18:23:26.152290+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/firstfile.py', '--cfg-path', '/var/folders/k9/54d2d9qd2nn0qz8m7425nxfm0000gn/T/tmptbb_kusc']
[2024-11-05T10:23:29.191-0800] {standard_task_runner.py:105} INFO - Job 6: Subtask run_query
[2024-11-05T10:23:29.247-0800] {task_command.py:467} INFO - Running <TaskInstance: aasnowflake_test_dag.run_query manual__2024-11-05T18:23:26.152290+00:00 [running]> on host mac.attlocal.net
[2024-11-05T10:23:29.307-0800] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='aasnowflake_test_dag' AIRFLOW_CTX_TASK_ID='run_query' AIRFLOW_CTX_EXECUTION_DATE='2024-11-05T18:23:26.152290+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-05T18:23:26.152290+00:00'
[2024-11-05T10:23:29.307-0800] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-11-05T10:23:29.308-0800] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-11-05T10:23:29.308-0800] {logging_mixin.py:190} INFO - Current task name:run_query state:running start_date:2024-11-05 18:23:29.172554+00:00
[2024-11-05T10:23:29.308-0800] {logging_mixin.py:190} INFO - Dag name:aasnowflake_test_dag and current dag run status:running
[2024-11-05T10:23:29.308-0800] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-05T10:23:29.309-0800] {sql.py:278} INFO - Executing: SELECT CURRENT_TIMESTAMP();
[2024-11-05T10:23:29.328-0800] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/saiprasadreddykolan/Documents/E-commerce_project/venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/Users/saiprasadreddykolan/Documents/E-commerce_project/venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/Users/saiprasadreddykolan/Documents/E-commerce_project/venv/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/Users/saiprasadreddykolan/Documents/E-commerce_project/venv/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/saiprasadreddykolan/Documents/E-commerce_project/venv/lib/python3.10/site-packages/airflow/providers/common/sql/operators/sql.py", line 279, in execute
    hook = self.get_db_hook()
  File "/Users/saiprasadreddykolan/Documents/E-commerce_project/venv/lib/python3.10/site-packages/airflow/providers/common/sql/operators/sql.py", line 190, in get_db_hook
    return self._hook
  File "/opt/homebrew/Cellar/python@3.10/3.10.15/Frameworks/Python.framework/Versions/3.10/lib/python3.10/functools.py", line 981, in __get__
    val = self.func(instance)
  File "/Users/saiprasadreddykolan/Documents/E-commerce_project/venv/lib/python3.10/site-packages/airflow/providers/common/sql/operators/sql.py", line 166, in _hook
    hook = self.get_hook(conn_id=conn_id, hook_params=self.hook_params)
  File "/Users/saiprasadreddykolan/Documents/E-commerce_project/venv/lib/python3.10/site-packages/airflow/providers/common/sql/operators/sql.py", line 158, in get_hook
    connection = BaseHook.get_connection(conn_id)
  File "/Users/saiprasadreddykolan/Documents/E-commerce_project/venv/lib/python3.10/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/Users/saiprasadreddykolan/Documents/E-commerce_project/venv/lib/python3.10/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `snowflake_default` isn't defined
[2024-11-05T10:23:29.335-0800] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-11-05T10:23:29.336-0800] {logging_mixin.py:190} INFO - Task start:2024-11-05 18:23:29.172554+00:00 end:2024-11-05 18:23:29.335751+00:00 duration:0.163197
[2024-11-05T10:23:29.336-0800] {logging_mixin.py:190} INFO - Task:<Task(SnowflakeOperator): run_query> dag:<DAG: aasnowflake_test_dag> dagrun:<DagRun aasnowflake_test_dag @ 2024-11-05 18:23:26.152290+00:00: manual__2024-11-05T18:23:26.152290+00:00, state:running, queued_at: 2024-11-05 18:23:26.179047+00:00. externally triggered: True>
[2024-11-05T10:23:29.336-0800] {logging_mixin.py:190} INFO - Failure caused by The conn_id `snowflake_default` isn't defined
[2024-11-05T10:23:29.337-0800] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=aasnowflake_test_dag, task_id=run_query, run_id=manual__2024-11-05T18:23:26.152290+00:00, execution_date=20241105T182326, start_date=20241105T182329, end_date=20241105T182329
[2024-11-05T10:23:29.344-0800] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-05T10:23:29.344-0800] {standard_task_runner.py:124} ERROR - Failed to execute job 6 for task run_query (The conn_id `snowflake_default` isn't defined; 87426)
Traceback (most recent call last):
  File "/Users/saiprasadreddykolan/Documents/E-commerce_project/venv/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/Users/saiprasadreddykolan/Documents/E-commerce_project/venv/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/Users/saiprasadreddykolan/Documents/E-commerce_project/venv/lib/python3.10/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/Users/saiprasadreddykolan/Documents/E-commerce_project/venv/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/Users/saiprasadreddykolan/Documents/E-commerce_project/venv/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/Users/saiprasadreddykolan/Documents/E-commerce_project/venv/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/Users/saiprasadreddykolan/Documents/E-commerce_project/venv/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/Users/saiprasadreddykolan/Documents/E-commerce_project/venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
  File "/Users/saiprasadreddykolan/Documents/E-commerce_project/venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/Users/saiprasadreddykolan/Documents/E-commerce_project/venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/Users/saiprasadreddykolan/Documents/E-commerce_project/venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/Users/saiprasadreddykolan/Documents/E-commerce_project/venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/Users/saiprasadreddykolan/Documents/E-commerce_project/venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/Users/saiprasadreddykolan/Documents/E-commerce_project/venv/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/Users/saiprasadreddykolan/Documents/E-commerce_project/venv/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/saiprasadreddykolan/Documents/E-commerce_project/venv/lib/python3.10/site-packages/airflow/providers/common/sql/operators/sql.py", line 279, in execute
    hook = self.get_db_hook()
  File "/Users/saiprasadreddykolan/Documents/E-commerce_project/venv/lib/python3.10/site-packages/airflow/providers/common/sql/operators/sql.py", line 190, in get_db_hook
    return self._hook
  File "/opt/homebrew/Cellar/python@3.10/3.10.15/Frameworks/Python.framework/Versions/3.10/lib/python3.10/functools.py", line 981, in __get__
    val = self.func(instance)
  File "/Users/saiprasadreddykolan/Documents/E-commerce_project/venv/lib/python3.10/site-packages/airflow/providers/common/sql/operators/sql.py", line 166, in _hook
    hook = self.get_hook(conn_id=conn_id, hook_params=self.hook_params)
  File "/Users/saiprasadreddykolan/Documents/E-commerce_project/venv/lib/python3.10/site-packages/airflow/providers/common/sql/operators/sql.py", line 158, in get_hook
    connection = BaseHook.get_connection(conn_id)
  File "/Users/saiprasadreddykolan/Documents/E-commerce_project/venv/lib/python3.10/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/Users/saiprasadreddykolan/Documents/E-commerce_project/venv/lib/python3.10/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `snowflake_default` isn't defined
[2024-11-05T10:23:29.366-0800] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-11-05T10:23:29.383-0800] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-05T10:23:29.384-0800] {local_task_job_runner.py:245} INFO - ::endgroup::
